import type { Metadata } from 'next';
import { Chela_One, Dela_Gothic_One, Roboto_Condensed } from 'next/font/google';
import './globals.css';
import { Providers } from '@/app/providers';

const chelaOne = Chela_One({ weight: ['400'], subsets: ['latin'], variable: '--font-chela' });
const delaGothicOne = Dela_Gothic_One({ weight: ['400'], subsets: ['latin'], variable: '--font-dela' });
const roboto = Roboto_Condensed({
  weight: ['400', '500', '700', '600', '800'],
  subsets: ['latin'],
  variable: '--font-roboto',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${chelaOne.variable} ${delaGothicOne.variable} ${roboto.variable} antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
